import wget
from PIL import Image
from PIL import ImageDraw, ImageEnhance
import os

CURR_DIR = os.getcwd()
skin = input("Enter Username:")
url = "https://minotar.net/skin/"+str(skin)+".png"
wget.download(url, './lib.png')
os.mkdir("tmp")
os.system("move lib.png tmp")
layer = input("\nIs this skin Single-Layer or Multi-Layer? [y/n]")
if layer == str("y") or layer == str("Y"):
    print("Converting...")
    img = Image.open(CURR_DIR+'/tmp/lib.png').convert("RGBA")
    LowL = img.crop((0, 48, 16, 64))
    LowR = img.crop((48, 48, 64, 64))
    CenterR = img.crop((0, 32, 64, 48))
    HeadPat = img.crop((32, 0, 64, 16))
    export = Image.new("RGBA", (64, 64), color=0)
    export.paste(img, (0,0), img)
    export.paste(LowL, (16,48), LowL)
    export.paste(LowR, (32,48), LowR)
    export.paste(CenterR, (0,16), CenterR)
    export.paste(HeadPat, (0,0), HeadPat)
    export = ImageEnhance.Brightness(export).enhance(0.7)
    export.save("OUT.png")
    os.system("RD /s /q tmp")
    print("Removing Transparency...")
    img = Image.open("out.png").convert("RGBA")
    background = Image.new('RGBA', img.size, (106,106,106))
    alpha_composite = Image.alpha_composite(background, img)
    alpha_composite.save('out.png')
    print("Transparency Removed!")
    print("Cleaning up Images...")
    crack = Image.open("out.png").convert("RGBA")
    crack1 = ImageDraw.Draw(crack)
    crack1.rectangle([(0, 48), (16, 64)], fill=(106,106,106), outline=None, width=0)
    crack1.rectangle([(48, 48), (64, 64)], fill=(106,106,106), outline=None, width=0)
    crack1.rectangle([(0, 32), (64, 48)], fill=(106,106,106), outline=None, width=0)
    crack1.rectangle([(32, 0), (64, 16)], fill=(106,106,106), outline=None, width=0)
    crack.save("out.png")
else:
    print("Removing Transparency...")
    img = Image.open(CURR_DIR+'/tmp/lib.png').convert("RGBA")
    img = ImageEnhance.Brightness(img).enhance(0.7)
    background = Image.new('RGBA', img.size, (106,106,106))
    alpha_composite = Image.alpha_composite(background, img)
    alpha_composite.save('out.png')
    os.system("RD /s /q tmp")
    print("Transparency Removed!")
